# Generated by Django 3.2.9 on 2022-01-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
